"""Reproduce the local-only YouTubeKit snapshot; no downloads during builds.

Usage: python3 scripts/vendor_native_audio.py /path/to/YouTubeKit
The input must be the pinned upstream commit. The generated Swift contains the
bundled JavaScript as Base64 data, so an injected dylib needs no resource bundle.
"""
from pathlib import Path
import base64
import hashlib
import re
import subprocess
import sys

PIN = "e5b7d0396ce12bf3444f0d209e8436c83373b7af"
source = Path(sys.argv[1]).resolve(strict=True)
actual = subprocess.check_output(["git", "-c", "safe.directory=" + source.as_posix(), "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
if actual != PIN:
    raise SystemExit(f"Expected YouTubeKit {PIN}; found {actual}")
def pinned_bytes(path):
    # Read the commit's blob, not the worktree: autocrlf or local edits must not
    # alter the generated resources or the recorded hashes on another platform.
    relative = path.relative_to(source).as_posix()
    return subprocess.check_output(["git", "-c", "safe.directory=" + source.as_posix(), "-C", str(source), "show", PIN + ":" + relative])
root = Path(__file__).resolve().parents[1]
target = root / "tweak/Sources/Features/NowPlaying"
parts = [f"// Generated by scripts/vendor_native_audio.py from YouTubeKit {PIN}.\n"
         "// MIT; see NativeAudioLicenses.txt. Local extraction only.\n"]
inputs = []
for path in sorted((source / "Sources/YouTubeKit").rglob("*.swift")):
    relative = path.relative_to(source / "Sources/YouTubeKit")
    if "Remote" in relative.parts or path.name in {"Method.swift", "WebSocket.swift", "URLSessionDelegates.swift", "AsyncCompatibility.swift"}:
        continue
    raw = pinned_bytes(path)
    value = raw.decode("utf-8").replace("\r\n", "\n")
    inputs.append((str(relative).replace("\\", "/"), hashlib.sha256(raw).hexdigest()))
    value = value.replace("URLSession.shared.data(", "SGNativeHTTP.data(")
    if path.name == "YouTube.swift":
        # Unsupported platforms fail at compile time instead of selecting a server.
        value = value.replace("self.methods = [.remote]", "self.methods = [.local]")
        begin = value.index("                case .remote(let serverURL):")
        end = value.index("                }", begin)
        value = value[:begin] + value[end:]
        # Upstream issue #141: compactMapping stream data and zipping the original
        # responses pairs the wrong videoInfo when one client returned no streams.
        value = value.replace("let allStreamingData = try await self.streamingData", "_ = try await self.streamingData")
        value = value.replace("for (streamingData, videoInfo) in zip(allStreamingData, videoInfos) {\n                        try await process(streamingData: streamingData, videoInfo: videoInfo)\n                    }", "for videoInfo in videoInfos {\n                        if let streamingData = videoInfo.streamingData {\n                            try await process(streamingData: streamingData, videoInfo: videoInfo)\n                        }\n                    }")
        # An audio resolver does not need an additional progressive-video request.
        value = value.replace("if !streams.contains(where: { $0.includesVideoAndAudioTrack }) {", "if !streams.contains(where: { $0.includesAudioTrack }) {")
        # Authentication/age-restricted sources remain an explicit unavailable state.
        begin = value.index("                try await bypassAgeGate()")
        end = value.index("\n            }\n        }\n    }", begin)
        value = value[:begin] + "                throw YouTubeKitError.videoAgeRestricted" + value[end:]
        begin = value.index("    private func bypassAgeGate()")
        end = value.index("    /// Interface to query both adaptive", begin)
        value = value[:begin] + value[end:]
    elif path.name == "Stream.swift":
        begin = value.index("    init(remoteStream: RemoteStream)")
        end = value.index("    /// whether the stream is DASH", begin)
        value = value[:begin] + value[end:]
    elif path.name == "SignatureSolver.swift":
        value = value.replace("guard let url = Bundle.module.url(forResource: name, withExtension: ext) else {", 'guard let src = SGNativeJSResources.source(name + "." + ext) else {')
        value = value.replace("            let src = try String(contentsOf: url, encoding: .utf8)\n", "")
    elif path.name == "Concurrency.swift":
        begin = value.index("    func concurrentMap<T: Sendable>")
        value = value[:begin] + """    // Structured child tasks inherit cancellation. The upstream unstructured
    // Task array kept HTTP requests running after the user paused the queue.
    func concurrentMap<T: Sendable>(_ transform: @escaping @Sendable (Element) async -> T) async -> [T] where Element: Sendable {
        await withTaskGroup(of: (Int, T).self) { group in
            for (index, element) in enumerated() {
                group.addTask { (index, await transform(element)) }
            }
            var values = [(Int, T)]()
            for await value in group { values.append(value) }
            return values.sorted { $0.0 < $1.0 }.map { $0.1 }
        }
    }
}
"""
    # Upstream files have file-scoped private types used through extensions; the
    # combined file retains those semantics while avoiding dozens of upload files.
    parts.append("\n// MARK: Upstream " + str(relative).replace("\\", "/") + "\n" + value)
parts.append("\nextension YouTube { public enum ExtractionMethod: Hashable, Sendable { case local } }\n"
             "extension [YouTube.ExtractionMethod] { public static var `default`: Self { [.local] } }\n")
combined = "\n".join(parts)
combined = "\n".join(line.rstrip(" \t") for line in combined.splitlines()) + "\n"
(target / "NativeYouTubeLocal.swift").write_text(combined, encoding="utf-8", newline="\n")
resources = ["// Generated pinned resources; see NativeAudioLicenses.txt.\nimport Foundation\nenum SGNativeJSResources {\n    static func source(_ name: String) -> String? {\n        let encoded: String\n        switch name {\n"]
for path in sorted((source / "Sources/YouTubeKit/Resources").glob("*.js")):
    value = pinned_bytes(path)
    inputs.append(("Resources/" + path.name, hashlib.sha256(value).hexdigest()))
    b64 = base64.b64encode(value).decode("ascii")
    resources.append('        case "' + path.name + '": encoded = "' + b64 + '"\n')
resources.append("        default: return nil\n        }\n        return Data(base64Encoded: encoded).flatMap { String(data: $0, encoding: .utf8) }\n    }\n}\n")
(target / "NativeYouTubeResources.swift").write_text("".join(resources), encoding="utf-8", newline="\n")
(target / "NativeAudioVendorPin.txt").write_text("https://github.com/alexeichhorn/YouTubeKit\ncommit " + PIN + "\n\n" + "\n".join(f"{sha}  {name}" for name, sha in inputs) + "\n", encoding="utf-8", newline="\n")
print("Generated local-only Swift and embedded resources from " + PIN)
